name: flutter_ecommerce_website_demo
description: An e-ccomerce website demo build with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.6
  colorful_safe_area: ^0.3.0
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  provider: ^6.0.2
  responsive_builder: ^0.4.1
  stacked: ^2.2.8
  stacked_services: ^0.8.16
  url_launcher: ^6.0.18

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  stacked_generator: ^0.5.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.svg
